intro del trabajo actual
tgc-utn/tgc-utn.github.io pull request #23
Opened 2021-04-13 04:47 UTC by Javier-Rotelli

actualizo links, dejo el esqueleto de la pagina de recursos de monogame

2021-04-13 06:02 UTC, rejurime requested changes

2021-04-13 06:02 UTC, rejurime commented on trabajo_actual/index.md
> +
Tantas lineas en blanco?

2021-04-13 06:02 UTC, rejurime commented on trabajo_actual/index.md
> +* [Visual Studio Community Edition](https://visualstudio.microsoft.com/vs/community/)
Esto ya no es asi necesariamente.

2021-04-13 06:02 UTC, rejurime commented on trabajo_actual/index.md
> +* Tutorial C# [Español](https://docs.microsoft.com/es-es/dotnet/csharp/tour-of-csharp/tutorials/) o [Ingles](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/)
ingles va con tilde.

2021-04-13 06:02 UTC, rejurime commented on trabajo_actual/index.md
> +### Diseño 3D:
Queremos poner este apartado? y con esta informacion?

2021-04-13 15:16 UTC, Javier-Rotelli commented on index.md
> +para aprobar la asignatura es necesario realizar un [trabajo practico integrador]({% link trabajo_actual/index.md %}) en el cual se implementan todos los conocimientos adquiridos durante la cursada y
jajajaja, no estoy 100% seguro de que quise hacer ahi. de hecho,m no llegue a algo que me convenza. si tenes una forma preferid, lo organizamos asi

2021-04-14 01:37 UTC, Javier-Rotelli commented on trabajo_actual/index.md
> +### Diseño 3D:
vuela, en algun futuro vemos de reincorporarlo, pero no aca

2021-04-15 01:38 UTC, rejurime approved these changes

2021-04-15 01:40 UTC, rejurime commented on index.md
> +para aprobar la asignatura es necesario realizar un [trabajo teorico practico integrador]({% link trabajo_actual/index.md %}) en el cual se implementan todos los conocimientos adquiridos durante la c
trabajo teórico práctico integrador

2021-04-15 01:41 UTC, rejurime commented on index.md
> +para aprobar la asignatura es necesario realizar un [trabajo teorico practico integrador]({% link trabajo_actual/index.md %}) en el cual se implementan todos los conocimientos adquiridos durante la c
y en el renglo de abajo :stuck_out_tongue_closed_eyes:

2021-04-15 01:41 UTC, rejurime commented on trabajo_actual/index.md
> +Tendrán que seleccionar el tema del desarrollo de una lista de opciones disponibles, donde cada una presentará los lineamientos y condiciones que deberán ser cumplidos y evaluados. Cada alumno debe i
inscribirse

2021-04-15 01:42 UTC, rejurime commented on trabajo_actual/index.md
> +  * [Rider](https://www.jetbrains.com/rider/) - necesita licencia educativa, se puede obtener con la cuenta de la UTN [aca](https://www.jetbrains.com/es-es/community/education/#students)
acá

2021-04-15 20:12 UTC, Javier-Rotelli commented on trabajo_actual/index.md
> +Tendrán que seleccionar el tema del desarrollo de una lista de opciones disponibles, donde cada una presentará los lineamientos y condiciones que deberán ser cumplidos y evaluados. Cada alumno debe i
```suggestion
Tendrán que seleccionar el tema del desarrollo de una lista de opciones disponibles, donde cada una presentará los lineamientos y condiciones que deberán ser cumplidos y evaluados. Cada alumno debe inscribirse en el siguiente *[https://docs.google.com/forms/d/e/1FAIpQLScBzqcmqcy5w6Rei-6CrZi4STqx6YGsxmVHTDHhz312n_B_zw/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLScBzqcmqcy5w6Rei-6CrZi4STqx6YGsxmVHTDHhz312n_B_zw/viewform?usp=sf_link)*
```

2021-04-15 20:13 UTC, Javier-Rotelli commented on trabajo_actual/index.md
> +  * [Rider](https://www.jetbrains.com/rider/) - necesita licencia educativa, se puede obtener con la cuenta de la UTN [aca](https://www.jetbrains.com/es-es/community/education/#students)
```suggestion
  * [Rider](https://www.jetbrains.com/rider/) - necesita licencia educativa, se puede obtener con la cuenta de la UTN [acá](https://www.jetbrains.com/es-es/community/education/#students) 
```

2021-04-15 20:14 UTC, Javier-Rotelli commented on index.md
> +para aprobar la asignatura es necesario realizar un [trabajo teorico practico integrador]({% link trabajo_actual/index.md %}) en el cual se implementan todos los conocimientos adquiridos durante la c
```suggestion
para aprobar la asignatura es necesario realizar un [trabajo teórico práctico integrador]({% link trabajo_actual/index.md %}) en el cual se implementan todos los conocimientos adquiridos durante la cursada y un parcial teórico práctico.
```

2021-04-15 20:15 UTC, merged