MonoGame Model Importing Tutorial
tgc-utn/tgc-utn.github.io pull request #42
Opened 2022-09-11 02:28 UTC by AVinitzca

- Added base model importing tutorial.
- Added assets for the importing tutorial.

2022-09-17 23:00 UTC, rejurime requested changes

2022-09-17 23:00 UTC, rejurime commented on _drafts/monogame-model-importing-tutorial.md
> +![MonoGame Content Editor](https://docs.monogame.net/images/MGCB-editor.png)
Ya que hay varias imagenes que estas subiendo a assets, creo que podria usar una mas del Editor y no depender de la de la doc que cada tanto cambian las cosas.

2022-09-18 20:03 UTC, AVinitzca commented on _drafts/monogame-model-importing-tutorial.md
> +Las fuentes de Modelos 3D pueden ser varias. Podemos crear nuestras propias geometrías, especificando atributos y creando índices para que cada primitiva -generalmente triángulos- sepa por qué vértic
Decís de poner 6 links uno abajo del otro?

2022-09-19 14:19 UTC, rejurime approved these changes

2022-09-19 14:20 UTC, merged